import { readdir, stat } from "node:fs/promises";
import { resolve } from "node:path";
import Link from "next/link";

export const metadata = {
  title: "Testing reports - django-login-app",
  description: "Local testing reports generated by C-API and C-UI.",
};

export const dynamic = "force-dynamic";

const REPORT_FILE_PATTERN =
  /^C-(API|UI)-(local|production)-\d{4}-\d{2}-\d{2}-\d{2}-\d{2}-\d{2}$/;

type TestingReport = {
  fileName: string;
  modifiedAt: string;
  size: number;
};

type ProductionTestingReport = {
  id: number;
  agent: string;
  environment: string;
  model: string;
  status: string;
  createdAt: string;
};

const API_BASE = (
  process.env.NEXT_PUBLIC_API_URL ||
  process.env.API_BACKEND_URL ||
  (process.env.VERCEL
    ? "https://django-login-api.vercel.app"
    : "http://127.0.0.1:8000")
).replace(/\/$/, "");

async function loadTestingReports(): Promise<TestingReport[]> {
  const repoRoot = resolve(process.cwd(), "..");
  const reportsDir = resolve(repoRoot, "allReports");

  try {
    const entries = await readdir(reportsDir);
    const reports = await Promise.all(
      entries
        .filter((entry) => REPORT_FILE_PATTERN.test(entry))
        .map(async (fileName) => {
          const fileStat = await stat(resolve(reportsDir, fileName));
          return {
            fileName,
            modifiedAt: fileStat.mtime.toISOString(),
            size: fileStat.size,
          };
        }),
    );
    return reports.sort((a, b) => b.modifiedAt.localeCompare(a.modifiedAt));
  } catch {
    return [];
  }
}

async function loadProductionTestingReports(): Promise<ProductionTestingReport[]> {
  try {
    const response = await fetch(
      `${API_BASE}/api/test-run-reports/?environment=production`,
      { cache: "no-store" },
    );
    if (!response.ok) {
      return [];
    }
    return (await response.json()) as ProductionTestingReport[];
  } catch {
    return [];
  }
}

function formatFileSize(size: number): string {
  if (size < 1024) {
    return `${size} B`;
  }
  return `${(size / 1024).toFixed(1)} KB`;
}

export default async function TestingReportsPage() {
  const isProduction = Boolean(process.env.VERCEL);
  const reports = isProduction
    ? await loadProductionTestingReports()
    : await loadTestingReports();

  return (
    <div className="findings-page">
      <header className="findings-header">
        <div className="findings-header-top">
          <h1>Testing reports</h1>
          <nav className="findings-nav" aria-label="Site navigation">
            <Link href="/">Sign in</Link>
            <Link href="/register">Register</Link>
            <Link href="/attempts">Login attempts</Link>
            <Link href="/testing-dashboard">Testing Dashboard</Link>
          </nav>
        </div>
        <p className="findings-subtitle">
          {isProduction ? (
            <>
              Production reports generated by the Testing Dashboard. These
              reports are stored in the production database.
            </>
          ) : (
            <>
              Local reports generated by the testing buttons on the Testing
              Dashboard. These files live in <code>allReports/</code> and are
              downloaded from the local app.
            </>
          )}
        </p>
      </header>

      <main className="findings-main">
        <section className="findings-section">
          {reports.length > 0 ? (
            <ul className="testing-report-list">
              {isProduction
                ? (reports as ProductionTestingReport[]).map((report) => (
                    <li key={report.id} className="testing-report-item">
                      <a href={`${API_BASE}/api/test-run-reports/${report.id}/download/`}>
                        {report.agent}-{report.environment}-
                        {new Date(report.createdAt)
                          .toISOString()
                          .slice(0, 19)
                          .replace("T", "-")
                          .replaceAll(":", "-")}
                      </a>
                      <span>
                        {report.status} · {report.model || "unknown model"} ·{" "}
                        {new Date(report.createdAt).toLocaleString()}
                      </span>
                    </li>
                  ))
                : (reports as TestingReport[]).map((report) => (
                    <li key={report.fileName} className="testing-report-item">
                      <a
                        href={`/api/agents/reports?file=${encodeURIComponent(report.fileName)}`}
                      >
                        {report.fileName}
                      </a>
                      <span>
                        {new Date(report.modifiedAt).toLocaleString()} ·{" "}
                        {formatFileSize(report.size)}
                      </span>
                    </li>
                  ))}
            </ul>
          ) : (
            <p className="findings-count-note">
              No testing reports found yet. Run C-API or C-UI from the Testing
              Dashboard to create one.
            </p>
          )}
        </section>
      </main>
    </div>
  );
}
