import { readdir, stat } from "node:fs/promises";
import { resolve } from "node:path";
import Link from "next/link";

export const metadata = {
  title: "Testing reports - django-login-app",
  description: "Local testing reports generated by C-API and C-UI.",
};

export const dynamic = "force-dynamic";

const REPORT_FILE_PATTERN =
  /^C-(API|UI)-(local|production)-\d{4}-\d{2}-\d{2}-\d{2}-\d{2}-\d{2}$/;

type TestingReport = {
  fileName: string;
  modifiedAt: string;
  size: number;
};

async function loadTestingReports(): Promise<TestingReport[]> {
  const repoRoot = resolve(process.cwd(), "..");
  const reportsDir = resolve(repoRoot, "allReports");

  try {
    const entries = await readdir(reportsDir);
    const reports = await Promise.all(
      entries
        .filter((entry) => REPORT_FILE_PATTERN.test(entry))
        .map(async (fileName) => {
          const fileStat = await stat(resolve(reportsDir, fileName));
          return {
            fileName,
            modifiedAt: fileStat.mtime.toISOString(),
            size: fileStat.size,
          };
        }),
    );
    return reports.sort((a, b) => b.modifiedAt.localeCompare(a.modifiedAt));
  } catch {
    return [];
  }
}

function formatFileSize(size: number): string {
  if (size < 1024) {
    return `${size} B`;
  }
  return `${(size / 1024).toFixed(1)} KB`;
}

export default async function TestingReportsPage() {
  const reports = await loadTestingReports();

  return (
    <div className="findings-page">
      <header className="findings-header">
        <div className="findings-header-top">
          <h1>Testing reports</h1>
          <nav className="findings-nav" aria-label="Site navigation">
            <Link href="/">Sign in</Link>
            <Link href="/register">Register</Link>
            <Link href="/attempts">Login attempts</Link>
            <Link href="/testing-dashboard">Testing Dashboard</Link>
          </nav>
        </div>
        <p className="findings-subtitle">
          Local reports generated by the testing buttons on the Testing
          Dashboard. These files live in <code>allReports/</code> and are
          downloaded from the local app.
        </p>
      </header>

      <main className="findings-main">
        <section className="findings-section">
          {reports.length > 0 ? (
            <ul className="testing-report-list">
              {reports.map((report) => (
                <li key={report.fileName} className="testing-report-item">
                  <a
                    href={`/api/agents/reports?file=${encodeURIComponent(report.fileName)}`}
                  >
                    {report.fileName}
                  </a>
                  <span>
                    {new Date(report.modifiedAt).toLocaleString()} ·{" "}
                    {formatFileSize(report.size)}
                  </span>
                </li>
              ))}
            </ul>
          ) : (
            <p className="findings-count-note">
              No testing reports found yet. Run a local C-API or C-UI test from
              the login page to create one.
            </p>
          )}
        </section>
      </main>
    </div>
  );
}
